version: '3'

services:
  web:
    build: .
    command: ./docker-entrypoint.sh "${PORT}"
    tty: true
    volumes:
      - .:/code
    ports:
      - "${PORT}:8000"
  redis:
    image: redis
    expose:
      - "6379"
