version: '3'

services:
  web:
    build: .
    command: ./docker-entrypoint.sh
    tty: true
    volumes:
      - .:/code
    ports:
      - "8000:8000"
  redis:
    image: redis
    expose:
      - "6379"
